# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r_github_packages:
  - jimhester/lintr
after_success:
  - Rscript -e 'rmarkdown::render("README.Rmd")'
  - Rscript -e 'lintr::lint_package'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
