language: r
sudo: false
cache: packages
r_github_packages:
- jimhester/lintr
after_success:
- Rscript -e 'rmarkdown::render("README.Rmd")'
- Rscript -e 'lintr::lint_package'
- Rscript -e 'covr::codecov()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
notifications:
  slack:
    secure: QTXAbFSPss8YSeIHHmc0SNqQbBz/0ES2rIt3TvghYn2zBlxdJqsJpyEwsreX43VKTT0MT6DWrqZUgioFwA7VzVzM1l62QtR8hKSmgexga2N3q/weoOToSNC/UuTA52i2cnH0IeafMSPlryYtwX9jlf2wkKP0sFgS1ehF+WffZthcz52qFOr2usTgkkNUYpcNzOfgPIBMxF/lGMDUgAEyFsKZeKRyhxQyvXby+eAdEbY4LIb8bDHldISxnOmrNDtHVRGA+fECyO9+eO99QOYGa0xaHUXpicVqzR5vcMTUOzDhBhmlNMGKEa0QXmaDFMyjhsLlGJd7MsVKuBYFW6ltiskUBMf56LG466AtJeZlq7vw3B7Ln7Y7g1ZV1l4fRwD/gs9mCpChhowNaVdw6ZkhJqq8KLzGPmYtM5JLk0Ybzmt5iQVUT3W2UC8EPw8Z3vJ7kAZ7L98z7nqoiDuwIFTQvMqe11eKAs+U3p3KGwNFr3wwv7pwMN64S5cDY2fM6xg5JhfZ1Iosb/TSiUqKenxeS/eaWwx9DliqIwP22HDNnbJNXX4IvN6Sa5y2Dhxs1KekDduUMD0YaNXo7Cq+ZQIMqQylJy2t4b7iD+RevGxXrvN8ddLIhLI1C2tqVrfX0nqhMKqh2OHU4lWkfQut8/ZFZ6L6FydRB702IFzSJZ7A0Pg=
