name: Build
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.1'
    - name: Setup Tex
      uses: r-lib/actions/setup-tinytex@v1
    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'
    - name: Install devtools
      run: R -e 'install.packages("devtools")'
    - name: Install R dependencies
      run: R -e 'devtools::install_deps(dep = T)'
    - name: Build the package
      run: R CMD build .
    - name: Run package checks
      run: R CMD check *tar.gz
    - name: Report Code Coverage
      run: Rscript -e 'covr::codecov()'
    - name: Build Github page
      run: Rscript -e 'pkgdown::build_site()'
    - name: Report build status via Slack
      uses: act10ns/slack@v1
      if: always()
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
